---
- name: Deploy systems with an example provisioning callback
  hosts: localhost
  vars_files:
    - sample_vars.yml
  tasks:
    - name: Create ssh key pair
      ec2_key:
        name: "{{ lab_name }}"
        region: "{{ region }}"
      register: create_key

    - name: save private key
      copy:
        content: "{{ create_key.key.private_key }}"
        dest: "{{ playbook_dir }}/{{ lab_name }}.pem"
        mode: '0400'
      when: create_key.changed

    - name: Get AMI images
      ec2_ami_facts:
        region: "{{ region }}"
        owner: 309956199498
        filters:
          name: "RHEL-7.6*GA*"
          architecture: "x86_64"
      register: amis
    
    - name: Create VPC if needed
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: 172.16.0.0/16
        region: "{{ region }}"
      register: vpc

    - name: Create subnet if needed
      ec2_vpc_subnet:
        state: present
        region: "{{ region }}"
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ vpc.vpc.cidr_block}}"
      register: subnet
    
    - name: create vpc internet gateway
      ec2_vpc_igw:
        region: "{{ region }}"
        vpc_id: "{{ vpc.vpc.id }}"
        tags:
          Name: "{{ lab_name }}"
      register: igw

    - name: This creates a default route (0.0.0.0/0) for the subnet to
      ec2_vpc_route_table:
        region: "{{ region }}"
        vpc_id: "{{ vpc.vpc.id }}"
        subnets:
          - "{{ subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
        tags:
          Name: "{{ lab_name }}"

    - include_tasks: provision.yml
      when: status == "up"
    
    - include_tasks: teardown.yml
      when: status == "down"
